apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
spec:
  generators:
  - git:
      repoURL: https://github.com/abkura/argokustomize-nested.git
      revision: HEAD
      directories:
      - path: applications/*
      - exclude: true
        path: applications/sample
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/abkura/argokustomize-nested.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          selfHeal: true