apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../jbosseap-base

namespace: sample

namePrefix: sample-b

commonLabels:
  application: sample-b
  
images:
- name: application-image
  newName: abkura/jboss-profiler
  newTag: latest